### ISSUE TITLE
Could you add a typewriter sound set?

### ISSUE THREAD

**Issue by olso** [airtoxin/Sublime-SoundSets#1]
Something like https://www.youtube.com/watch?v=BldzubYpwvg :)

**Comment by airtoxin** [comment]
It sounds good.
I try to search free typewriter sound.

**Comment by airtoxin** [comment]
@olso 
Add https://github.com/airtoxin/Sublime-SoundSets/commit/f85924eebc6cb9a82128f82e912e733676672e9c

**Comment by olso** [comment]
Nice :+1:

**Comment by niguang1024** [comment]
Mechanical Keyboard sound also

**Comment by airtoxin** [comment]
:ok: 
but you can do it by put off your earphone. haha :)

**Comment by olso** [comment]
@airtoxin do you think its possible to have this for webstorm (anything jetbrains) or atom?

**Comment by olso** [comment]
This plugin as whole

**Comment by airtoxin** [comment]
@olso this plugin only for Sublime.
but I want implent same functional plugin for Atom editor.
